name: Analyze YouTube Videos and Update Notion

on:
  schedule:
    - cron: '0 9 * * 1'
      timezone: 'Europe/Madrid'
  workflow_dispatch:

jobs:
  analyze-videos:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
      - name: Installed dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt       
      - name: Set environment variables
        env: 
          PROXY_USERNAME: ${{ secrets.PROXY_USERNAME }}
          PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          NOTION_URL: ${{ secrets.NOTION_URL }}
          NOTION_VERSION: ${{ secrets.NOTION_VERSION }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_ORGANIZATION: ${{ secrets.OPENAI_API_ORGANIZATION }}
          OPENAI_API_PROJECT: ${{ secrets.OPENAI_API_PROJECT }}  
        run:  |
          python app.py
